name: Sample Python GitHub
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  contents: read #Ability to read the contents permission
  security-events: write # Required for uploading code scanning 
jobs:
    build-publish-python:
        runs-on: ubuntu-latest
        env:
          PLATFORM_REPO: 'pypi-buildtests-local'
          RESOLVE_REPO: 'pypi-buildtests-remote'
          DOCKER_REPO: 'docker-pypibuildtests-local'
          IMAGE_NAME: 'python-test-image-gh'
        outputs:
          image: ${{ vars.JF_URL }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}
          digest: ${{ steps.build.outputs.digest }}
        steps:
            # Download the JFrog CLI and configure using JFrog Project and OIDC provider 
            - uses: jfrog/setup-jfrog-cli@v4
              name: Setup JFrog CLI
              id: setup-cli
              env:
                #JF_URL value is the JPD subdomain. It must exclude protocol (e.g. my-instance-name.jfrog.io)
                JF_URL: https://${{ vars.JF_URL }}/
                JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
                # Docker section start
                #   JF_USER is used for basic authentication to docker repositories
                JF_USER: ${{ secrets.JF_USER }}
                # Docker section end

              with:
                version: latest
                  
            - name: Checkout the repository    
              uses: actions/checkout@v4
           
            - name: configure jfrog environment
              run: |
                jf pip-config --repo-resolve=${{ env.RESOLVE_REPO }}
                
            - name: configure environment
              run: |                      
                python3 -m pip install --upgrade pip setuptools wheel sigstore
                wheel -h
                pip show setuptools
                echo $VIRTUAL_ENV
                
            - name: build project
              run: |                      
                jf pip install -r requirements.txt  --module=jfrog-python-example
                python setup.py sdist bdist_wheel
                cd dist && echo "hashes=$(sha256sum * | base64 -w0)" >> $GITHUB_OUTPUT

            - name: publish python package
              run: |
                jf rt u dist/ ${{ env.PLATFORM_REPO }}/example-projects/ --module=jfrog-python-example
                
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3    
                
            - name: Authenticate Docker
              uses: docker/login-action@v3
              with:
                registry: ${{ vars.JF_URL }}
                username: ${{ secrets.JF_USER }}
                password: ${{ secrets.JF_PASSWORD }}
                
            - name: Build Docker image    
              uses: docker/build-push-action@v6
              id: build
              with:
                push: true
                platforms: linux/amd64 #, linux/arm64
                tags: ${{ vars.JF_URL }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}   

            - name: add docker package to build
              run: |  
                 echo "${{ vars.JF_URL }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}" > metadata.json
                 jf rt build-docker-create ${{ env.DOCKER_REPO }} --image-file metadata.json 
                 
            - name: publish build info
              run: |
                      jf rt build-collect-env 
                      jf rt build-add-dependencies .
                      jf rt build-add-git
                      jf rt build-publish
                
            - name: build scan
              run: |            
                jf build-scan --fail=false
            
    provenance:
      needs: [build-publish-python]
      uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.10.0
      with:
        image:  ${{ needs.build-publish-python.outputs.image }}
        digest: ${{ needs.build-publish-python.outputs.digest }}
        private-repository: true
      secrets:
        registry-username: ${{ secrets.JF_USER }}
        registry-password: ${{ secrets.JF_PASSWORD }}
